### ISSUE TITLE
Create function to remove leading slashes from a path

### ISSUE THREAD

**Issue by skleinjung** [twin-digital/coco-toolbox#47]
We need a function to remove the leading slash from a path string if it has one. No unit tests are needed.

**Comment by coco-b0t** [comment]
#### Issue Status: **canceled**



#### Recent Activity

None

**Comment by coco-b0t** [comment]
I encountered an error while providing feedback: Unexpected token T in JSON at position 16

**Comment by skleinjung** [comment]
Try again.

**Comment by coco-b0t** [comment]
I encountered an error while providing feedback: Unexpected token S in JSON at position 0

**Comment by skleinjung** [comment]
retry

**Comment by skleinjung** [comment]
retry

**Comment by coco-b0t** [comment]
I encountered an error while providing feedback: Unexpected token S in JSON at position 0

**Comment by skleinjung** [comment]
Can you implement this?

**Comment by coco-b0t** [comment]
Yes, I can implement this. However, I need more information to ensure that I fully understand the requirements.

**Comment by skleinjung** [comment]
such as?

**Comment by coco-b0t** [comment]
Here are some questions that could help clarify the requirements:

- What programming language and framework should be used to implement this function?
- What is the expected input format for the path? Is it a string or an object?
- Are there any constraints on the length or format of the path?
- Should the function modify the original path or return a new path with the leading slashes removed?
- What is the expected output format for the path? Should it be a string or an object?
- Are there any edge cases or error scenarios that the function needs to handle? For example, what if the path is empty or contains only slashes?

**Comment by skleinjung** [comment]
here is that enw issue

**Comment by coco-b0t** [comment]
Title: Create function to remove leading slashes from a path
Description:

Create a function that takes a string representing a path as input and returns the same path but with any leading slashes removed. The function should not modify the original string. For example, if the input is "/home/user/documents", the function should return "home/user/documents". If the input is "documents", the function should return "documents". The function should handle edge cases such as empty strings and strings consisting only of slashes. The function should be implemented in Typescript and added to the "coco-toolbox" project. 

Please let me know if you need any further information.
